### ISSUE TITLE
error: package android.support.annotation does not exist | cannot find symbol class Nullable

### ISSUE THREAD

**Issue by rfdc** [Driversnote-Dev/react-native-kontaktio#61]
Hi there,
I've started a fresh react-native project and got the following error:

```
error: package android.support.annotation does not exist
error: cannot find symbol class Nullable
```
This is a picture of the error:
![image](https://user-images.githubusercontent.com/32999759/63831738-e62ae800-c9a1-11e9-9ed7-a8c9b804a00e.png)

These are my dependencies:
```
"dependencies": {
    "react": "16.8.6",
    "react-native": "0.60.5",
    "react-native-kontaktio": "^2.6.2",
    "react-native-switch-toggle": "^1.1.0"
  },
  "devDependencies": {
    "@babel/core": "^7.5.5",
    "@babel/runtime": "^7.5.5",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.8.0",
    "eslint": "^6.1.0",
    "jest": "^24.8.0",
    "metro-react-native-babel-preset": "^0.56.0",
    "react-test-renderer": "16.8.6"
  },
```

I've tried to use `npm & yarn` and both gave the same error.

Any idea on how to solve this issue?

Thanks

**Comment by Andruschenko** [comment]
Thanks for posting the issue. The module is currently not yet tested with `react-native` version `0.60`. As soon as it will be new, installation instructions for that version will be posted. In the meantime it's probably safer to stick to React Native `0.59`. 

If you get it to run on React Native `0.60`, please tell us what you did or even better, file a PR. PRs are very much appreciated!

**Comment by rfdc** [comment]
Hi @Andruschenko, It worked with React Native `0.59` - Thanks
